#!/bin/bash

echo "🌡️ 极端高温避暑安置系统"
echo "========================"
echo ""

echo "📋 项目结构:"
echo "  backend/    - NestJS 后端服务"
echo "  frontend/   - Next.js 14 前端应用"
echo ""

echo "🚀 启动步骤:"
echo ""
echo "1️⃣  启动数据库:"
echo "    docker compose up -d postgres"
echo ""
echo "2️⃣  安装依赖:"
echo "    npm install"
echo ""
echo "3️⃣  启动后端 (端口 4000):"
echo "    npm run dev:backend"
echo ""
echo "4️⃣  启动前端 (端口 3000):"
echo "    npm run dev:frontend"
echo ""
echo "5️⃣  或者同时启动前后端:"
echo "    npm run dev"
echo ""
echo "🌐 访问地址:"
echo "  前端: http://localhost:3000"
echo "  后端: http://localhost:4000"
echo ""
echo "📖 功能模块:"
echo "  📍 点位管理    - 街道发布避暑点位"
echo "  👥 重点人群    - 社区登记重点关注人员"
echo "  ✅ 进站登记    - 人员进出站登记管理"
echo "  📦 物资管理    - 仓库物资库存管理"
echo "  🚚 物资调拨    - 物资调拨配送管理"
echo "  📞 回访提醒    - 离站未确认人员回访"
echo "  📋 补货单      - 库存不足自动补货"
echo ""
