export enum LocationStatus {
  OPEN = 'open',
  FULL = 'full',
  CLOSED = 'closed',
}

export enum PersonPriority {
  HIGH = 'high',
  MEDIUM = 'medium',
  LOW = 'low',
}

export enum CheckInStatus {
  CHECKED_IN = 'checked_in',
  CHECKED_OUT = 'checked_out',
  LEFT_UNCONFIRMED = 'left_unconfirmed',
}

export enum MaterialCategory {
  DRINKING_WATER = 'drinking_water',
  MEDICINE = 'medicine',
  FOOD = 'food',
  OTHER = 'other',
}

export enum AllocationStatus {
  PENDING = 'pending',
  IN_TRANSIT = 'in_transit',
  DELIVERED = 'delivered',
  CANCELLED = 'cancelled',
}

export enum FollowUpStatus {
  PENDING = 'pending',
  COMPLETED = 'completed',
  NO_ANSWER = 'no_answer',
  NEEDS_ASSISTANCE = 'needs_assistance',
}

export enum ContactResult {
  ARRIVED_SAFE = 'arrived_safe',
  NOT_ARRIVED = 'not_arrived',
  NO_ANSWER = 'no_answer',
  WRONG_NUMBER = 'wrong_number',
  OTHER = 'other',
}

export enum ReplenishmentStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  ORDERED = 'ordered',
  RECEIVED = 'received',
  CANCELLED = 'cancelled',
}

export interface Location {
  id: string;
  name: string;
  address: string;
  street: string;
  community: string;
  capacity: number;
  currentOccupancy: number;
  status: LocationStatus;
  facilities?: string;
  openTime?: string;
  closeTime?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Person {
  id: string;
  name: string;
  idCard: string;
  phone: string;
  address: string;
  community: string;
  priority: PersonPriority;
  medicalConditions?: string;
  emergencyContact?: string;
  emergencyPhone?: string;
  isCurrentlyCheckedIn: boolean;
  checkInRecords?: CheckInRecord[];
  followUps?: FollowUp[];
  createdAt: string;
  updatedAt: string;
}

export interface CheckInRecord {
  id: string;
  personId: string;
  locationId: string;
  checkInTime: string;
  checkOutTime?: string;
  status: CheckInStatus;
  notes?: string;
  followUpReminderSent: boolean;
  person?: Person;
  location?: Location;
  createdAt: string;
}

export interface Material {
  id: string;
  name: string;
  category: MaterialCategory;
  unit: string;
  quantity: number;
  safetyStock: number;
  lowStockAlert: boolean;
  specifications?: string;
  storageLocation?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Allocation {
  id: string;
  materialId: string;
  fromLocation: string;
  toLocationId: string;
  quantity: number;
  status: AllocationStatus;
  remarks?: string;
  dispatchedAt?: string;
  deliveredAt?: string;
  material?: Material;
  toLocation?: Location;
  createdAt: string;
}

export interface FollowUp {
  id: string;
  personId: string;
  checkInRecordId?: string;
  status: FollowUpStatus;
  notes?: string;
  followUpTime?: string;
  needsFurtherAction: boolean;
  isDepartureFollowUp: boolean;
  contactResult?: ContactResult;
  departureRemarks?: string;
  person?: Person;
  checkInRecord?: CheckInRecord;
  createdAt: string;
}

export interface Replenishment {
  id: string;
  materialId: string;
  requestedQuantity: number;
  approvedQuantity?: number;
  status: ReplenishmentStatus;
  reason?: string;
  supplier?: string;
  expectedDelivery?: string;
  autoGenerated: boolean;
  material?: Material;
  createdAt: string;
}

export interface Statistics {
  locations?: {
    total: number;
    open: number;
    full: number;
    closed: number;
    totalPeople: number;
    totalCapacity: number;
  };
  people?: {
    total: number;
    highPriority: number;
    mediumPriority: number;
    lowPriority: number;
    currentlyIn: number;
  };
  checkIns?: {
    todayCheckIns: number;
    todayCheckOuts: number;
    currentlyIn: number;
    unconfirmed: number;
  };
  materials?: {
    total: number;
    lowStock: number;
    totalQuantity: number;
    drinkingWaterQuantity: number;
    medicineQuantity: number;
  };
  allocations?: {
    total: number;
    pending: number;
    inTransit: number;
    delivered: number;
    cancelled: number;
    todayAllocations: number;
  };
  followUps?: {
    total: number;
    pending: number;
    completed: number;
    needsAssistance: number;
  };
  replenishments?: {
    total: number;
    pending: number;
    approved: number;
    ordered: number;
    received: number;
    autoGenerated: number;
  };
}
