'use client';

import { useEffect, useState } from 'react';
import {
  Group,
  Title,
  Text,
  Button,
  Table,
  Paper,
  Modal,
  Select,
  NumberInput,
  Textarea,
  ActionIcon,
  notifications,
  Badge,
  Alert,
} from '@mantine/core';
import { useForm } from '@mantine/form';
import { IconPlus, IconCheck, IconX, IconFileInvoice, IconAlertTriangle } from '@tabler/icons-react';
import { api } from '@/lib/api';
import { StatusBadge } from '@/components/StatusBadge';
import { Replenishment, ReplenishmentStatus, Material } from '@/types';

export default function ReplenishmentsPage() {
  const [replenishments, setReplenishments] = useState<Replenishment[]>([]);
  const [materials, setMaterials] = useState<Material[]>([]);
  const [loading, setLoading] = useState(true);
  const [modalOpen, setModalOpen] = useState(false);
  const [filterStatus, setFilterStatus] = useState<string>('');

  const form = useForm({
    initialValues: {
      materialId: '',
      requestedQuantity: 50,
      reason: '',
      supplier: '',
    },
  });

  useEffect(() => {
    loadData();
  }, [filterStatus]);

  async function loadData() {
    try {
      const params = filterStatus ? { status: filterStatus } : {};
      const [replenishmentsData, materialsData] = await Promise.all([
        api.replenishments.getAll(params),
        api.materials.getAll(),
      ]);
      setReplenishments(replenishmentsData);
      setMaterials(materialsData);
    } catch (error: any) {
      notifications.show({ title: '加载失败', message: error.message, color: 'red' });
    } finally {
      setLoading(false);
    }
  }

  async function handleSubmit(values: any) {
    try {
      await api.replenishments.create({ ...values, autoGenerated: false });
      notifications.show({ title: '成功', message: '补货单已创建', color: 'green' });
      setModalOpen(false);
      form.reset();
      loadData();
    } catch (error: any) {
      notifications.show({ title: '创建失败', message: error.message, color: 'red' });
    }
  }

  async function handleUpdateStatus(id: string, status: ReplenishmentStatus, approvedQuantity?: number) {
    try {
      const data: any = { status };
      if (approvedQuantity !== undefined) {
        data.approvedQuantity = approvedQuantity;
      }
      await api.replenishments.update(id, data);
      notifications.show({ title: '成功', message: '状态已更新', color: 'green' });
      loadData();
    } catch (error: any) {
      notifications.show({ title: '操作失败', message: error.message, color: 'red' });
    }
  }

  async function handleCancel(id: string) {
    if (!confirm('确定要取消这个补货单吗？')) return;
    try {
      await api.replenishments.cancel(id);
      notifications.show({ title: '成功', message: '补货单已取消', color: 'green' });
      loadData();
    } catch (error: any) {
      notifications.show({ title: '操作失败', message: error.message, color: 'red' });
    }
  }

  const pendingCount = replenishments.filter((r) => r.status === ReplenishmentStatus.PENDING).length;
  const autoGeneratedCount = replenishments.filter((r) => r.autoGenerated).length;
  const lowStockMaterials = materials.filter((m) => m.lowStockAlert);

  return (
    <div>
      <Group justify="space-between" mb="xl">
        <div>
          <Title order={2}>补货单管理</Title>
          <Text size="sm" c="dimmed">物资库存低于安全线时自动生成补货单</Text>
        </div>
        <Group>
          <Select
            placeholder="筛选状态"
            clearable
            value={filterStatus}
            onChange={(value) => setFilterStatus(value || '')}
            data={[
              { value: ReplenishmentStatus.PENDING, label: '待审批' },
              { value: ReplenishmentStatus.APPROVED, label: '已批准' },
              { value: ReplenishmentStatus.ORDERED, label: '已下单' },
              { value: ReplenishmentStatus.RECEIVED, label: '已收货' },
            ]}
            style={{ width: 120 }}
          />
          <Button leftSection={<IconPlus size="1rem" />} onClick={() => setModalOpen(true)}>
            手动补货
          </Button>
        </Group>
      </Group>

      {pendingCount > 0 && (
        <Alert
          icon={<IconAlertTriangle size="1rem" />}
          title="待审批补货单"
          color="yellow"
          mb="xl"
        >
          <Group gap="lg">
            <Text size="sm">
              有 <strong>{pendingCount}</strong> 个补货单待审批
            </Text>
            <Text size="sm">
              自动生成: <strong>{autoGeneratedCount}</strong> 个
            </Text>
          </Group>
        </Alert>
      )}

      {lowStockMaterials.length > 0 && (
        <Alert color="red" mb="xl">
          <Text size="sm" fw={500} mb="xs">当前库存不足的物资：</Text>
          <Group gap="md">
            {lowStockMaterials.map((m) => (
              <Badge key={m.id} color="red" size="md">
                {m.name}: {m.quantity} / {m.safetyStock}
              </Badge>
            ))}
          </Group>
        </Alert>
      )}

      <Paper withBorder radius="md">
        <Table>
          <Table.Thead>
            <Table.Tr>
              <Table.Th>物资</Table.Th>
              <Table.Th>申请数量</Table.Th>
              <Table.Th>状态</Table.Th>
              <Table.Th>原因</Table.Th>
              <Table.Th>创建时间</Table.Th>
              <Table.Th>操作</Table.Th>
            </Table.Tr>
          </Table.Thead>
          <Table.Tbody>
            {replenishments.map((rep) => (
              <Table.Tr key={rep.id}>
                <Table.Td>
                  <Group>
                    <IconFileInvoice size="1rem" color="#1677ff" />
                    <Text fw={500}>{rep.material?.name}</Text>
                    {rep.autoGenerated && (
                      <Badge color="blue" size="xs">自动生成</Badge>
                    )}
                  </Group>
                  <StatusBadge status={rep.material?.category || 'other'} />
                </Table.Td>
                <Table.Td>
                  <Text fw={700}>
                    {rep.approvedQuantity || rep.requestedQuantity} {rep.material?.unit}
                  </Text>
                  {rep.approvedQuantity && rep.approvedQuantity !== rep.requestedQuantity && (
                    <Text size="xs" c="dimmed">
                      申请: {rep.requestedQuantity} {rep.material?.unit}
                    </Text>
                  )}
                </Table.Td>
                <Table.Td>
                  <StatusBadge status={rep.status} />
                </Table.Td>
                <Table.Td>
                  <Text size="sm">{rep.reason || '-'}</Text>
                </Table.Td>
                <Table.Td>
                  <Text size="sm">{new Date(rep.createdAt).toLocaleString('zh-CN')}</Text>
                </Table.Td>
                <Table.Td>
                  <Group gap="xs">
                    {rep.status === ReplenishmentStatus.PENDING && (
                      <>
                        <Button
                          size="xs"
                          variant="light"
                          color="green"
                          leftSection={<IconCheck size="0.8rem" />}
                          onClick={() => handleUpdateStatus(rep.id, ReplenishmentStatus.APPROVED, rep.requestedQuantity)}
                        >
                          批准
                        </Button>
                        <ActionIcon color="red" onClick={() => handleCancel(rep.id)}>
                          <IconX size="1rem" />
                        </ActionIcon>
                      </>
                    )}
                    {rep.status === ReplenishmentStatus.APPROVED && (
                      <Button
                        size="xs"
                        variant="light"
                        color="violet"
                        onClick={() => handleUpdateStatus(rep.id, ReplenishmentStatus.ORDERED)}
                      >
                        已下单
                      </Button>
                    )}
                    {rep.status === ReplenishmentStatus.ORDERED && (
                      <Button
                        size="xs"
                        variant="light"
                        color="green"
                        leftSection={<IconCheck size="0.8rem" />}
                        onClick={() => handleUpdateStatus(rep.id, ReplenishmentStatus.RECEIVED)}
                      >
                        确认收货
                      </Button>
                    )}
                  </Group>
                </Table.Td>
              </Table.Tr>
            ))}
          </Table.Tbody>
        </Table>
      </Paper>

      <Modal
        opened={modalOpen}
        onClose={() => setModalOpen(false)}
        title="手动创建补货单"
        size="lg"
      >
        <form onSubmit={form.onSubmit(handleSubmit)}>
          <Select
            label="选择物资"
            placeholder="请选择需要补货的物资"
            data={materials.map((m) => ({
              value: m.id,
              label: `${m.name} (当前: ${m.quantity} ${m.unit}, 安全线: ${m.safetyStock})`,
            }))}
            {...form.getInputProps('materialId')}
            mb="md"
            required
            searchable
          />
          <Group grow mb="md">
            <NumberInput
              label="申请数量"
              placeholder="请输入补货数量"
              min={1}
              {...form.getInputProps('requestedQuantity')}
              required
            />
            <TextInput
              label="供应商"
              placeholder="供应商名称（可选）"
              {...form.getInputProps('supplier')}
            />
          </Group>
          <Textarea
            label="补货原因"
            placeholder="请说明补货原因"
            {...form.getInputProps('reason')}
            mb="md"
          />
          <Group justify="flex-end" mt="xl">
            <Button variant="subtle" onClick={() => setModalOpen(false)}>取消</Button>
            <Button type="submit">创建补货单</Button>
          </Group>
        </form>
      </Modal>
    </div>
  );
}
