import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { Material } from './material.entity';

export enum ReplenishmentStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  ORDERED = 'ordered',
  RECEIVED = 'received',
  CANCELLED = 'cancelled',
}

@Entity('replenishments')
export class Replenishment {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  materialId: string;

  @Column({ type: 'int' })
  requestedQuantity: number;

  @Column({ type: 'int', nullable: true })
  approvedQuantity: number;

  @Column({
    type: 'enum',
    enum: ReplenishmentStatus,
    default: ReplenishmentStatus.PENDING,
  })
  status: ReplenishmentStatus;

  @Column({ type: 'text', nullable: true })
  reason: string;

  @Column({ type: 'text', nullable: true })
  supplier: string;

  @Column({ type: 'timestamp', nullable: true })
  expectedDelivery: Date;

  @Column({ default: true })
  autoGenerated: boolean;

  @ManyToOne(() => Material)
  @JoinColumn({ name: 'materialId' })
  material: Material;

  @CreateDateColumn()
  createdAt: Date;
}
