import { IsUUID, IsInt, IsOptional, IsString, IsEnum, IsBoolean } from 'class-validator';
import { ReplenishmentStatus } from '../../entities/replenishment.entity';

export class CreateReplenishmentDto {
  @IsUUID()
  materialId: string;

  @IsInt()
  requestedQuantity: number;

  @IsString()
  @IsOptional()
  reason?: string;

  @IsString()
  @IsOptional()
  supplier?: string;

  @IsBoolean()
  @IsOptional()
  autoGenerated?: boolean;
}

export class UpdateReplenishmentDto {
  @IsEnum(ReplenishmentStatus)
  @IsOptional()
  status?: ReplenishmentStatus;

  @IsInt()
  @IsOptional()
  approvedQuantity?: number;

  @IsString()
  @IsOptional()
  supplier?: string;
}

export class ReplenishmentQueryDto {
  @IsUUID()
  @IsOptional()
  materialId?: string;

  @IsEnum(ReplenishmentStatus)
  @IsOptional()
  status?: ReplenishmentStatus;
}
