import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Replenishment, ReplenishmentStatus } from '../entities/replenishment.entity';
import { Material } from '../entities/material.entity';
import { CreateReplenishmentDto, UpdateReplenishmentDto, ReplenishmentQueryDto } from './dto/replenishment.dto';

@Injectable()
export class ReplenishmentService {
  constructor(
    @InjectRepository(Replenishment)
    private replenishmentRepository: Repository<Replenishment>,
    @InjectRepository(Material)
    private materialRepository: Repository<Material>,
  ) {}

  async create(createDto: CreateReplenishmentDto): Promise<Replenishment> {
    const material = await this.materialRepository.findOne({
      where: { id: createDto.materialId },
    });
    if (!material) {
      throw new NotFoundException(`物资 ${createDto.materialId} 不存在`);
    }

    const replenishment = this.replenishmentRepository.create({
      ...createDto,
      status: ReplenishmentStatus.PENDING,
      autoGenerated: createDto.autoGenerated ?? false,
    });

    return this.replenishmentRepository.save(replenishment);
  }

  async autoGenerateIfNeeded(material: Material): Promise<Replenishment | null> {
    if (!material.lowStockAlert) {
      return null;
    }

    const existingPending = await this.replenishmentRepository.findOne({
      where: {
        materialId: material.id,
        status: ReplenishmentStatus.PENDING,
        autoGenerated: true,
      },
    });

    if (existingPending) {
      return null;
    }

    const existingApproved = await this.replenishmentRepository.findOne({
      where: {
        materialId: material.id,
        status: ReplenishmentStatus.APPROVED,
        autoGenerated: true,
      },
    });

    if (existingApproved) {
      return null;
    }

    const existingOrdered = await this.replenishmentRepository.findOne({
      where: {
        materialId: material.id,
        status: ReplenishmentStatus.ORDERED,
        autoGenerated: true,
      },
    });

    if (existingOrdered) {
      return null;
    }

    const suggestedQuantity = Math.max(
      material.safetyStock * 2 - material.quantity,
      material.safetyStock,
    );

    return this.create({
      materialId: material.id,
      requestedQuantity: suggestedQuantity,
      reason: `库存低于安全线（当前: ${material.quantity}, 安全线: ${material.safetyStock}），自动生成补货单`,
      autoGenerated: true,
    });
  }

  async findAll(query?: ReplenishmentQueryDto): Promise<Replenishment[]> {
    const qb = this.replenishmentRepository.createQueryBuilder('replenishment');

    if (query?.materialId) {
      qb.andWhere('replenishment.materialId = :materialId', { materialId: query.materialId });
    }
    if (query?.status) {
      qb.andWhere('replenishment.status = :status', { status: query.status });
    }

    qb.leftJoinAndSelect('replenishment.material', 'material')
      .orderBy('replenishment.createdAt', 'DESC');

    return qb.getMany();
  }

  async findOne(id: string): Promise<Replenishment> {
    const replenishment = await this.replenishmentRepository.findOne({
      where: { id },
      relations: ['material'],
    });
    if (!replenishment) {
      throw new NotFoundException(`补货单 ${id} 不存在`);
    }
    return replenishment;
  }

  async update(id: string, updateDto: UpdateReplenishmentDto): Promise<Replenishment> {
    const replenishment = await this.findOne(id);

    if (
      updateDto.status === ReplenishmentStatus.RECEIVED &&
      replenishment.status !== ReplenishmentStatus.RECEIVED
    ) {
      const quantity = replenishment.approvedQuantity || replenishment.requestedQuantity;
      await this.materialRepository.increment(
        { id: replenishment.materialId },
        'quantity',
        quantity,
      );

      const material = await this.materialRepository.findOne({
        where: { id: replenishment.materialId },
      });
      if (material) {
        material.lowStockAlert = material.quantity <= material.safetyStock;
        await this.materialRepository.save(material);
      }
    }

    Object.assign(replenishment, updateDto);
    return this.replenishmentRepository.save(replenishment);
  }

  async cancel(id: string): Promise<Replenishment> {
    const replenishment = await this.findOne(id);
    if (replenishment.status === ReplenishmentStatus.RECEIVED) {
      throw new BadRequestException('已收货的补货单不能取消');
    }
    replenishment.status = ReplenishmentStatus.CANCELLED;
    return this.replenishmentRepository.save(replenishment);
  }

  async getStatistics(): Promise<any> {
    const [total, pending, approved, ordered, received, autoGenerated] = await Promise.all([
      this.replenishmentRepository.count(),
      this.replenishmentRepository.count({ where: { status: ReplenishmentStatus.PENDING } }),
      this.replenishmentRepository.count({ where: { status: ReplenishmentStatus.APPROVED } }),
      this.replenishmentRepository.count({ where: { status: ReplenishmentStatus.ORDERED } }),
      this.replenishmentRepository.count({ where: { status: ReplenishmentStatus.RECEIVED } }),
      this.replenishmentRepository.count({ where: { autoGenerated: true } }),
    ]);

    return {
      total,
      pending,
      approved,
      ordered,
      received,
      autoGenerated,
    };
  }
}
